version: '2'
services:
  # API Services
  cart:
    build:
      context: .
      dockerfile: ./api/cart/Dockerfile
    links:
      - "storage"
  product:
    build:
      context: .
      dockerfile: ./api/product/Dockerfile
  search:
    build:
      context: .
      dockerfile: ./api/search/Dockerfile
  stock:
    build:
      context: .
      dockerfile: ./api/stock/Dockerfile
  user:
    build:
      context: .
      dockerfile: ./api/user/Dockerfile
    links:
      - "storage"
  wishlist:
    build:
      context: .
      dockerfile: ./api/wishlist/Dockerfile
    links:
      - "storage"
  # App Storage
  storage:
    build: ./storage
  # App Web UI
  web:
    build: ./web
    ports:
      - "3000:3000"
    links:
      - "cart"
      - "product"
      - "search"
      - "stock"
      - "user"
      - "wishlist"
  # App Proxy
  proxy:
    build: ./proxy
    ports:
      - "9999:9999"
    links:
      - "cart"
      - "product"
      - "search"
      - "stock"
      - "user"
      - "wishlist"
